// YOUTUBE CONSTANTS
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const ADD_TWEETS = 'ADD_TWEETS';
export const SET_FOLLOW = 'SET_FOLLOW';
export const TWITTER_ERROR = 'TWITTER_ERROR';
export const TWITTER_CLEAR = 'TWITTER_CLEAR';
// YOUTUBE CONSTANTS
export const ADD_YT_ACCOUNT = 'ADD_YT_ACCOUNT';
export const ADD_YT_DATA = 'ADD_YT_DATA';
export const SET_YT_FOLLOW = 'SET_YT_FOLLOW';
export const YT_ERROR = 'YT_ERROR';
export const YT_CLEAR = 'YT_CLEAR';
// COMMON CONSTANTS
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_LOADING = 'SET_LOADING';
export const ADD_FOLLOWING_ACCOUNTS = 'ADD_FOLLOWING_ACCOUNTS';





